name: unit tests for api.mon-menu.app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Start Docker
        run: docker run --name tests postgres
        
      - name: Run tests
        run: npm test
